index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: courses
        permanent: true

courses:
  path: /courses
  controller: App\Controller\CourseController::index

